name: test-build-latex

on: push

env:
    SOURCE_NAME: main

jobs:
  build-pdflatex:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Build pdfLaTeX
      run: |
        latexmk -pdf -bibtex -gg -jobname=%A-pdflatex $SOURCE_NAME.tex
    - uses: actions/upload-artifact@v2
      with:
        name: $SOURCE_NAME-pdflatex
        path: |
          $SOURCE_NAME-pdflatex.pdf
          $SOURCE_NAME-pdflatex.log
  
  build-xelatex:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Build XeLaTeX
      run: |
        latexmk -pdfxe -bibtex -gg -jobname=%A-xelatex $SOURCE_NAME.tex
    - uses: actions/upload-artifact@v2
      with:
        name: $SOURCE_NAME-xelatex
        path: |
          $SOURCE_NAME-xelatex.pdf
          $SOURCE_NAME-xelatex.log
